// <auto-generated />
namespace IQMStarterKit.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class NewFilterForFullName : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(NewFilterForFullName));
        
        string IMigrationMetadata.Id
        {
            get { return "201705140021128_NewFilterForFullName"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
