// <auto-generated />
namespace IQMStarterKit.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;

    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddFilePaths : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddFilePaths));
        
        string IMigrationMetadata.Id
        {
            get { return "201706030417082_AddFilePaths"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
