// <auto-generated />
namespace IQMStarterKit.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;

    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addGroupTutorModel : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addGroupTutorModel));
        
        string IMigrationMetadata.Id
        {
            get { return "201706140936347_addGroupTutorModel"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
