// <auto-generated />
namespace IQMStarterKit.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;

    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class update_temp_tables : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(update_temp_tables));
        
        string IMigrationMetadata.Id
        {
            get { return "201705190435039_update_temp_tables"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
